# Generated by Django 4.2 on 2023-05-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link_id",
            field=models.BigIntegerField(),
        ),
    ]
