# Generated by Django 4.2 on 2023-05-03 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0003_alter_link_link_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="redirects",
        ),
    ]
