# Generated by Django 4.2 on 2023-05-03 18:12

from django.db import migrations, models
import links.models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0004_remove_link_redirects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="expires_at",
            field=models.DateTimeField(default=links.models.calculate_expiration_date),
        ),
    ]
