# Generated by Django 4.2 on 2023-05-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0005_alter_link_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="link_id",
            field=models.CharField(max_length=15),
        ),
    ]
